image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

before_build:
  chmod +x gradlew
  
build_script:
  - chmod +x gradlew #  предоставление прав на запуск файла gradlew
  - ./gradlew test --info "-Dselenide.headless=true"
